spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blackflag_cms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: blackflag

knife4j:
  # 聚合swagger文档
  gateway:
    # 指定手动配置的模式(默认为该模式)
    strategy: manual
    routes:
      - name: 系统服务
        # 真实子服务访问url地址-提供OpenAPI的文档
        url: /system/v3/api-docs?group=default
        service-name: system
        order: 2
        context-path: /system
      - name: 用户服务
        url: /user/v3/api-docs?group=default
        service-name: user
        order: 3
        context-path: /user
      - name: 社区服务
        url: http://localhost:8083/community/v3/api-docs?group=default
        service-name: community
        order: 4
        context-path: /community