# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
  port: 8080
  servlet:
    context-path: /gateway
    session:
      cookie:
        http-only: true

spring:
  profiles:
    active: dev
